# Generated by Django 2.2.6 on 2019-12-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='storyvotes',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='hacker_news.Story'),
        ),
    ]
