# Generated by Django 2.2.6 on 2019-12-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0002_allow_url_content_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='url',
            field=models.URLField(max_length=1024, null=True),
        ),
    ]
