# Generated by Django 2.2.6 on 2019-12-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hacker_news', '0005_fill_posted_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='posted',
            field=models.DateTimeField(),
        ),
    ]
